module.exports = {
  serverError: "Internal server error",
  emailExists: "Email already exists.",
  phoneExists: "Mobile number already exists.",
  login: "Logged in successfully.",
  passReset: "Password has been reset successfully. Please login again.",
  passResetLogin: "Password has been changed. Please login again.",
  passChange: "Password changed successfully.",
  passNotChange: "Password not changed.",
  pass_wrong: "Wrong password.",
  adminNot: "Admin not found,please login again.",
  userRegister: "User registered successfully.",
  passMatch: "Please enter correct old password.",
  noUser: "User not found.",
  passwordUpdate: "Password can't be updated.",
  userUpdate: "User details updated successfully.",
  botUpdate: "Bot details updated successfully.",
  userBlocked: "User blocked successfully.",
  userunBlocked: "User unblocked successfully.",
  wrongEmail: "User not exists with this email address.",
  registerEmail: "Please enter a registered email address.",
  wrongPassword: "Invalid password.",
  userLogin: "User login successfully.",
  userNot: "User not found,please login again.",
  userFetched: "User fetched succesfully.",
  profileFetch: "Profile fetched succesfully.",
  forgotLink: "Reset password link has been sent to registered email address.",
  emailVerify: "Email verified successfully.",
  emailVerifyal: "Email already verified.",
  otpVerify: "Otp verified successfully.",
  wrongOtp: "Please enter correct otp.",
  wrongOtpal: "Otp already verified.",
  emailNotverify: "Can't login as email not verified.",
  otpNotverify: "Can't login as otp not verified.",
  msgSent: "Message sent successfully.",
  userId: "This userId already exists.",
  statusNot: "Status not found.",
  requestAccept: "Request accepted successfully.",
  requestReject: "Request rejected  successfully.",
  dataFetch: "Data fetched successfully.",
  invalidId: "Please enter valid id.",
  acceptAl: "Request already accepted.",
  rejectAl: "Request already rejected.",
  billingSave: "Billing details saved successfully.",
  passErr: "Old password and new password should not be the same.",
  authRequire: "Authorization token required",
  dashFetch: "Dashboard details fetched successfully.",
  userBlock: "Cannot login user blocked by admin.",
  noData: "No data found.",
  forgotLinkal:
    "Reset password link has been already sent to registered email address",
  linkexpire: "This link is expired",
  deviceErr: "Account has been login into another device",
  linkValid: "This forgot password link is valid",
  wrongJwt: "Invalid token",
  wrongAuth: "Invalid authorization format",
  ticketAlready: "Ticket already canceled.",
  ticketCancel:
    "Ticket cancel request sent successfully please wait for approval by admin.",
  ticketCancelaccept: "Ticket cancel request accepted successfully.",
  ticketCancelreject: "Ticket cancel request rejected successfully.",
  ticketAcceptalr: "Ticket cancel request already accepted.",
  ticketRejectalr: "Ticket cancel request  already rejected.",
  courierDetails: "Courier details added successfully.",
  statusChange: "Status changed successfully.",
  seasonTicketupdate: "Season ticket details updated successfully.",
  emailNotregister: "This email address is not registered with us.",
  stationsFetchedSuccessfully: "Station list fetched successfully.",
  stationListNotFetched: "Unable to fetch station list.",
  cardSaved: "Card details added successfully.",
  addSeasonTicket: "Season ticket details fetched successfully.",
  removeCardDetails: "Credit card details remove successfully.",
  paymentSuccessfully: "Payment done successfully.",
  ticketBookedSuccessfully: "Ticket has been booked successfully.",
  ticketNotBooked: "Unable to book ticket. Olease try again.",
  invalidBookingType: "Please enter valid booking type.",
  trainsFetchedSuccessfully: "Trains list fetched successfully.",
  trainsNotFetched: "Unable to fetch trains list. Please ty again.",
  bookingDetailsFetched: "Booking details fetched successfully.",
  bookingDetailsNotFetched:
    "Unable to fetch booking details. Please try again.",
  bookingCancelled: "Booking has been cancelled successfully.",
  bookingNotCancelled: "Unable to cancel booking. Please try again.",
  bookingNotFound: "Booking not found.",
  bookingAlreadyCancelled: "Booking has been already cancelled.",
  bookingSearch: "Fares fetched successfully.",
  bookingDetails: "Booking details fetched successfully.",
  stopPointFetched: "Stop points fetched successfully",
  stopPointNotFetched: "Unable to fetch stop points. Please try again.",
  infoSaved: "Information has been saved successfully.",
  infoNotSaved: "Unable to save information. Please try again.",
  alreadyMarkedAsPaid: "Booking has been already marked as paid.",
  markedAsPaid: "Booking has been marked as paid.",
  notMarkedAsPaid: "Unbale to update paid status. Please try again.",
  alreadyDelivered: "Card has been already delivered.",
};
